version: "3.1"
services:
    web:
        build: ./web
        ports: 
            - "3000:3000"
            - "443:443"
        volumes:
            - ./web:/usr/src/app
        links:
            - db
        restart: on-failure
        networks:
            - default
    client:
        build: ./client
        ports: 
            - "8080:8080"
        volumes:
            - ./client:/usr/src/client
    db:
        build: ./db
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - TZ=Africa/Casablanca
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: tirach
            MYSQL_PASSWORD: rach
            MYSQL_ROOT_PASSWORD: rach
volumes:
    persistent:
